### ISSUE TITLE
Fix README on pypi

### ISSUE THREAD

**Issue by rhamzeh** [openfga/python-sdk#2]
We published [v0.0.1](https://pypi.org/project/openfga-sdk/0.0.1/), but it does not have the proper README in the published package - we should fix that.

e.g.
```py
from setuptools import setup

# read the contents of your README file
from pathlib import Path
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

setup(
    name='an_example_package',
    # other arguments omitted
    long_description=long_description,
    long_description_content_type='text/markdown'
)
```

https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

**Comment by adriantam** [comment]
The problem is not that it does not have README - more like the spacing is incorrect.

**Comment by rhamzeh** [comment]
Here's an example project: https://pypi.org/project/broote/
