### ISSUE TITLE
README: use different code block for different read API configuration

### ISSUE THREAD

**Issue by adriantam** [openfga/python-sdk#26]
The READMEs' read relationship tuples example uses the same code block for different read API configuration (i.e., find if a relationship tuple stating that a certain user is a viewer of certain document, find all relationship tuples where a certain user has a relationship as any relation to a certain document, etc.)

Ideally, each type of API will have its own code block to improve reading experience.

For example,

```python
# Find if a relationship tuple stating that a certain user is a viewer of certain document
body = TupleKey(
    user="user:81684243-9356-4421-8fbf-a4f8d36aa31b",
    relation="viewer",
    object="document:roadmap",
)

response = await fga_client.read(body)
# response = ReadResponse({"tuples": [Tuple({"key": TupleKey({"user":"...","relation":"...","object":"..."}), "timestamp": datetime.fromisoformat("...") })]})

```

```python
# Find all relationship tuples where a certain user has a relationship as any relation to a certain document
body = TupleKey(
    user="user:81684243-9356-4421-8fbf-a4f8d36aa31b",
    object="document:roadmap",
)

response = await fga_client.read(body)
# response = ReadResponse({"tuples": [Tuple({"key": TupleKey({"user":"...","relation":"...","object":"..."}), "timestamp": datetime.fromisoformat("...") })]})

```

The code in question is in https://github.com/openfga/python-sdk/blob/1f4c73467f13ed3bcd1989a6051695c4abac3c41/README.md?plain=1#L388.  

Ideally, we will also fix the [SDK generator](https://github.com/openfga/sdk-generator/blob/fa95282bd686061d54859f6685b32b8b1a0c41ac/config/clients/python/template/README_calling_api.mustache#L175) so that newly generated python SDKs will have the corresponding changes. This is tracked as https://github.com/openfga/sdk-generator/issues/126. However, if that is difficult to do, simply focusing on the Python SDK side https://github.com/openfga/python-sdk/blob/main/README.md will help us as well.

**Comment by akj2018** [comment]
Hi, @adriantam I would like work on this issue. Please assign it to me.
Thank you!
