### ISSUE TITLE
README: double slash used as comments in example

### ISSUE THREAD

**Issue by adriantam** [openfga/python-sdk#27]
Some of the README examples are incorrect in that double slash `//` are used in place of `#` as comments.

The offending lines are 
- [ ] https://github.com/openfga/python-sdk/blob/1f4c73467f13ed3bcd1989a6051695c4abac3c41/README.md?plain=1#L413
- [ ] https://github.com/openfga/python-sdk/blob/1f4c73467f13ed3bcd1989a6051695c4abac3c41/README.md?plain=1#L683

Ideally, we will also fix the SDK generator [here](https://github.com/openfga/sdk-generator/blob/fa95282bd686061d54859f6685b32b8b1a0c41ac/config/clients/python/template/README_calling_api.mustache#L201) and [here](https://github.com/openfga/sdk-generator/blob/fa95282bd686061d54859f6685b32b8b1a0c41ac/config/clients/python/template/README_calling_api.mustache#L471) so that newly generated python SDKs will have the corresponding changes. This is tracked as https://github.com/openfga/sdk-generator/issues/126. However, if that is difficult to do, simply focusing on the Python SDK side https://github.com/openfga/python-sdk/blob/main/README.md will help us as well.

**Comment by Harshal662** [comment]
i can do that

**Comment by rhamzeh** [comment]
We have a PR (#30) fixing this already from another community member, but thank you for your interest!
