### ISSUE TITLE
README: add import and client initialization as comments for each code block

### ISSUE THREAD

**Issue by adriantam** [openfga/python-sdk#28]
In the SDK README, for each code block examples, it will be helpful if
- [ ] import modules are noted as comments
- [ ] client initialization are noted as comments

For example, 

```
body = CreateStoreRequest(
    name = "FGA Demo Store",
)
response = await fga_client.create_store(body)
# response.id = "01FQH7V8BEG3GPQW93KTRFR8JB"
```

should be 

```
#from openfga_sdk.client import OpenFgaClient
#from openfga_sdk.models.create_store_request import CreateStoreRequest

# initialize fga_client
body = CreateStoreRequest(
    name = "FGA Demo Store",
)
response = await fga_client.create_store(body)
# response.id = "01FQH7V8BEG3GPQW93KTRFR8JB"

```

We want to do this for the examples listed in https://github.com/openfga/python-sdk/blob/main/README.md.  Ideally, we will also fix the [SDK generator](https://github.com/openfga/sdk-generator/blob/fa95282bd686061d54859f6685b32b8b1a0c41ac/config/clients/python/template/README_calling_api.mustache) so that newly generated python SDKs will have the corresponding changes. This is tracked as https://github.com/openfga/sdk-generator/issues/126. However, if that is difficult to do, simply focusing on the Python SDK side https://github.com/openfga/python-sdk/blob/main/README.md will help us as well.

**Comment by JRudransh** [comment]
Any Update on my PR?

**Comment by rhamzeh** [comment]
Thanks for the PR @JRudransh - we won't get to reviewing it this week as the team is busy in an offsite, but we'll be taking a look early next week.

**Comment by JRudransh** [comment]
PR  #63 Fixes this Issue
