### ISSUE TITLE
list_relations body definition might have wrong class "ClientListObjectsRequest" vs "ClientListRelationsRequest"

### ISSUE THREAD

**Issue by fschulte-eiwa** [openfga/python-sdk#54]
https://github.com/openfga/python-sdk/blame/addcb450b595aba453e57c2341f2fd08d0b77625/openfga_sdk/client/client.py#L611

**Comment by rhamzeh** [comment]
Yes, it is incorrect! Thanks for the report, will be fixed in the upcoming release in early Jan
