### ISSUE TITLE
Support for conditions?

### ISSUE THREAD

**Issue by alsyia** [openfga/python-sdk#60]
By submitting an issue to this repository, you agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/rfcs/blob/main/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'd like the Python SDK to support conditions. According to the [official documentation](https://openfga.dev/docs/modeling/conditions), this is not supported yet. Is there any plans to do so, and if yes, under which timeframe?

Thanks! :)

**Comment by rhamzeh** [comment]
Hi @alsyia - we're actively working on this, and they should be supported in the next release of the Python SDK.

Most likely, that will be this week

**Comment by alsyia** [comment]
Thanks for the quick answer! Looking forward to the release :)
