### ISSUE TITLE
OpenTelemetry instrumentation

### ISSUE THREAD

**Issue by dacevedo12** [openfga/python-sdk#91]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

Given how important is to keep authorization performant, it'd be great if the sdk was instrumented so one could see traces of authorization calls, checks, writes, etc.

### Describe the ideal solution

Instrument the sdk with OpenTelemetry

### Alternatives and current workarounds

Write a custom instrumentation relying on monkey-patching techniques or instrument at the application level.

### References

https://github.com/open-telemetry/opentelemetry-python

**Comment by aaguiarz** [comment]
Thanks @dacevedo12 !

This is already in our roadmap, we'll start working on it in the next couple of weeks. We'll start with the Python SDK.

https://github.com/openfga/roadmap/issues/41

**Comment by evansims** [comment]
This feature shipped in [v0.6](https://github.com/openfga/python-sdk/releases) and has received a number of improvements since then. We'll continue iterating upon it. Thanks for your suggestion!
